### PR TITLE
fix(replicator): updateTableMetrics is using too much postgresql CPU

### LINKED ISSUE #1763: bug(replicator): updateTableMetrics is using too much postgresql CPU
**What is the bug?**
the [updateTableMetrics function](https://github.com/farcasterxyz/hub-monorepo/blob/ac861b1236029acbb007456a3f53647d875030d2/apps/replicator/src/hubReplicator.ts#L43) is planned to be called every 5 seconds and each call uses an average of 2.82 minutes of CPU on a gcp 2VCPU / 8 GB RAM instance.
That's not sustainable and a waste of CPU.

**How can it be reproduced? (optional)**
Just start the replicator.

**Additional context (optional)**
I see two possible quick fixes:
* Stop counting the rows if STATSD_HOST is undefined
* Using [estimates](https://wiki.postgresql.org/wiki/Count_estimate) instead of count(*)

Here is the query:
```
SELECT
  (
  SELECT
    COALESCE(COUNT(*), $1) AS "chain_events"
  FROM
    "chain_events") AS "chain_events",
  (
  SELECT
    COALESCE(COUNT(*), $2) AS "fids"
  FROM
    "fids") AS "fids",
  (
  SELECT
    COALESCE(COUNT(*), $3) AS "signers"
  FROM
    "signers") AS "signers",
  (
  SELECT
    COALESCE(COUNT(*), $4) AS "username_proofs"
  FROM
    "username_proofs") AS "username_proofs",
  (
  SELECT
    COALESCE(COUNT(*), $5) AS "fnames"
  FROM
    "fnames") AS "fnames",
  (
  SELECT
    COALESCE(COUNT(*), $6) AS "messages"
  FROM
    "messages") AS "messages",
  (
  SELECT
    COALESCE(COUNT(*), $7) AS "casts"
  FROM
    "casts") AS "casts",
  (
  SELECT
    COALESCE(COUNT(*), $8) AS "reactions"
  FROM
    "reactions") AS "reactions",
  (
  SELECT
    COALESCE(COUNT(*), $9) AS "links"
  FROM
    "links") AS "links",
  (
  SELECT
    COALESCE(COUNT(*), $10) AS "verifications"
  FROM
    "verifications") AS "verifications",
  (
  SELECT
    COALESCE(COUNT(*), $11) AS "user_data"
  FROM
    "user_data") AS "user_data",
  (
  SELECT
    COALESCE(COUNT(*), $12) AS "storage_allocations"
  FROM
    "storage_allocations") AS "storage_allocations"
```
Parameter is `0`.

### PR DESCRIPTION
**Pull request by saez0pub**
## Motivation

the [updateTableMetrics function](https://github.com/farcasterxyz/hub-monorepo/blob/ac861b1236029acbb007456a3f53647d875030d2/apps/replicator/src/hubReplicator.ts#L43) is planned to be called every 5 seconds and each call uses an average of 2.82 minutes of CPU on a gcp 2VCPU / 8 GB RAM instance.
That's not sustainable and a waste of CPU.

Fixes #1763.

## Change Summary

* Stop counting the rows if STATSD_HOST is undefined
* Using [estimates](https://wiki.postgresql.org/wiki/Count_estimate) instead of count(*)

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [X] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [X] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [x] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR includes [documentation](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#32-writing-docs) if necessary.
- [X] All [commits have been signed](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#22-signing-commits)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

---

## PR-Codex overview
This PR optimizes `updateTableMetrics` in `hubReplicator.ts` to reduce PostgreSQL CPU usage by using table row count estimates.

### Detailed summary
- Added `getEstimateOfTablesRowCount` function in `db.ts` to fetch table row count estimates
- Updated `updateTableMetrics` in `hubReplicator.ts` to use row count estimates for monitoring tables

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

File: apps/replicator/src/hubReplicator.ts [hunk 1]
```diff
@@ -61,33 +63,26 @@ export class HubReplicator {
...
+      "casts",
+      "reactions",
+      "links",
+      "verifications",
+      "userData",
+      "storageAllocations",
+    ];
+    const stats = await getEstimateOfTablesRowCount(this.db, tablesToMonitor);
+    for (const row of stats.rows) {
+      if (row.estimate < 0) {
```
Comment (sds) [inline apps/replicator/src/hubReplicator.ts:82]: Interesting that an estimate could be < 0. No action required, just found it curious.

**Review by sds — APPROVED** [review]
Thank you!

File: apps/replicator/src/hubReplicator.ts (hunk 1 above)
Comment (saez0pub) [reply apps/replicator/src/hubReplicator.ts:82]: Yes, at startup, it is -1.
